mod transaction_create_admin;
mod data_persistence;
mod admin;
mod transaction;
mod transaction_delete_admin;
mod transaction_create_profile;
mod profile;
mod transaction_update_profile;
mod transaction_delete_profile;
mod transaction_add_resume;
mod resume;
mod entity;
mod admin_transaction_persistence;
mod admin_transaction_repository;
mod profile_transaction_persistence;
mod profile_transaction_repository;
mod resume_transaction_persistence;
mod resume_transaction_repository;
mod transaction_delete_resume;
mod transaction_update_resume;
mod transaction_add_skill;
mod skill;
mod skill_transaction_repository;
mod skill_transaction_persistence;
mod transaction_delete_skill;
mod transaction_update_skill;
fn main() {
    println!("Hello, world!");
}
